version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: printeast-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-printeast}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - printeast-network

  redis:
    image: redis:alpine
    container_name: printeast-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - printeast-network

volumes:
  postgres_data:
  redis_data:


networks:
  printeast-network:
    driver: bridge
